version: '3.8'

services:
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: 'istrac'
      MYSQL_USER: 'istrac'
      MYSQL_PASSWORD: 'istrac'
      MYSQL_ROOT_PASSWORD: 'istrac'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
