# Generated by Django 5.0 on 2024-01-04 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/')),
                ('tplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='api.tplace')),
            ],
        ),
    ]
